name: Check Liquibase Annotations
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  job-name:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:

      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        id: ident
        with:
          PATTERNS: '*.sql'
          RELATIVE: 'Database/Migration'
      - run: echo ${{ env.GIT_DIFF }}. 
      - run: echo "MIGRATION_DIFF=$(eval echo ${{ env.GIT_DIFF }})" >> $GITHUB_ENV
      
      - name: Migrations files changes.
        run: echo $MIGRATION_DIFF 


      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        id: ident2
        with:
          PATTERNS: '*.sql'
          RELATIVE: 'Database/Seeders'
      - run: echo ${{ env.GIT_DIFF }}. 
      - run: echo "SEEDERS_DIFF=$(eval echo ${{ env.GIT_DIFF }})" >> $GITHUB_ENV
      
      - name: Seeders files changes.
        run: echo $SEEDERS_DIFF    

      - run: filepath=`pwd` && echo "DIR=$filepath" >> $GITHUB_ENV 
      
      - name: Root path.
        run: echo $DIR         

      - name: Check SQL files.
        uses: FreddyJoseMedina/hello-world-javascript-action@v2.4
        with:
          new-migrations: ${{ env.MIGRATION_DIFF }}
          new-seeders: ${{ env.SEEDERS_DIFF }}
          dir: ${{ env.DIR }}

      
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const template = 'https://github.com/wbdt-sie/brainiac-api-monolith/blob/develop/database/liquibase_template.sql';
            const success = '${{ job.status }}' === 'success';
            const body = `The Workflow -> ${name} has: ${success ? 'succeeded ✅' : 'failed ❌'}\nPlease use the following template: ${template}\n\nMore details at: ${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            }) 
