name: Check Liquibase Annotations
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  job-name:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:

      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        id: ident
        with:
          PATTERNS: '*.sql'
          RELATIVE: 'Database/Migration'
      - run: echo ${{ env.GIT_DIFF }}. 
      - run: echo "MIGRATION_DIFF=$(eval echo ${{ env.GIT_DIFF }})" >> $GITHUB_ENV
      
      - name: Migrations files changes.
        run: echo $MIGRATION_DIFF 


      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        id: ident2
        with:
          PATTERNS: '*.sql'
          RELATIVE: 'Database/Seeders'
      - run: echo ${{ env.GIT_DIFF }}. 
      - run: echo "SEEDERS_DIFF=$(eval echo ${{ env.GIT_DIFF }})" >> $GITHUB_ENV
      
      - name: Seeders files changes.
        run: echo $SEEDERS_DIFF    

      - run: filepath=`pwd` && echo "DIR=$filepath" >> $GITHUB_ENV 
      
      - name: Root path.
        run: echo $DIR         

      - name: Check SQL files.
        id: validator
        uses: ./.github/actions/sql-validator
        with:
          new-migrations: ${{ env.MIGRATION_DIFF }}
          new-seeders: ${{ env.SEEDERS_DIFF }}
          dir: ${{ env.DIR }}
          feature-flag: true

      - run: echo "The result was ${{ steps.validator.outputs.successful-validation }}"
        name: Print result
        if: always()

      
      - name: Add comment to PR
        uses: actions/github-script@v6
        if: always()
        with:
          script: |
            const name = '${{ github.workflow   }}';
            const url = '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}';
            const success = ${{ steps.validator.outputs.successful-validation }};
            const body = `The Workflow -> ${name} has: ${success ? 'succeeded ✅' : 'failed ❌'}\n\nMore details at: ${url}`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            }) 
