name: hello-world-II
on:
  push:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@${GITHUB_REF}
        with:
          sparse-checkout: |
            Database
      - name: Say Hello
        run: echo "Hello world!"
      - name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      - name: check dir
        run: ls
      - name: check Database
        run: cd Database && ls        
      - name: check date
        run: date
      - name: Say Goodbye
        run: echo "Goodbye!"
