name: hello-world-II
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
      - name: Say Hello
        run: echo "Hello world!"
      - name: Do stuff
        run: |
          echo "Step 1..."
          echo "Step 2..."
          echo "Step 3..."
      - name: check dir
        run: ls
      - name: check Database
        run: cd Database && ls
      - name: check grep
        run: |
          i=0 && keyWord=='--liquibase formatted sql'
          cd Database && 
          for file in *; do
          [ -f "$file" ] || continue
          IFS= read -r line < "$file" || [ -n "$line" ] || continue
          case $line in
          ("$keyWord");; *) echo "$file" No match Liquibase Annotation on first line.;;
          esac
          done && echo $i   
      - name: check date
        run: date
      - name: Say Goodbye
        run: echo "Goodbye!"
