name: SQL validator worklow
on:
  pull_request:
    types: 
      - opened
      - synchronize
      - reopened
jobs:

  SQL-validator:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    
    steps:
      
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        name: Fetch Migrations changes
        with:
          PATTERNS: '*.sql'
          RELATIVE: 'database/migrations' 
     
      - run: echo "MIGRATION_DIFF=$(eval echo ${{ env.GIT_DIFF }})" >> $GITHUB_ENV
        name: Creating MIGRATION_DIFF variable
      
      - name: Migrations files changes.
        run: echo $MIGRATION_DIFF 

      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6
        name: Fetch Seeders changes
        with:
          PATTERNS: '*.sql'
          RELATIVE: 'database/seeders'

      - run: echo "SEEDERS_DIFF=$(eval echo ${{ env.GIT_DIFF }})" >> $GITHUB_ENV
        name: Creating SEEDERS_DIFF variable
      
      - name: Seeders files changes.
        run: echo $SEEDERS_DIFF    

      - run: filepath=`pwd` && echo "DIR=$filepath" >> $GITHUB_ENV
        name: Creating DIR variable
      
      - name: Root path.
        run: echo $DIR         

      - name: Validate SQL files.
        id: validator
        uses: ./.github/actions/sql-validator
        with:
          new-migrations: ${{ env.MIGRATION_DIFF }}
          new-seeders: ${{ env.SEEDERS_DIFF }}
          dir: ${{ env.DIR }}
          feature-flag: true
          token: ${{ secrets.GITHUB_TOKEN }}
          pass-emoji: ':white_check_mark:'
          fail-emoji: ':x:'
          job-url: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
